name: Tests
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-22.04

    services:
      mongodb:
        image: mongo:7.0.11
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: admin
          MONGO_INITDB_DATABASE: JestDB
        ports:
          - 27017:27017
        options: >-
          --health-cmd mongosh
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v3

      - name: Initalize MongoDB
        run: |
          mongosh --host localhost:27017 -u admin -p admin --authenticationDatabase admin <<EOF
            db = db.getSiblingDB('JestDB');
            db.createUser({ user: 'testing', pwd: 'testing', roles: [{ role: 'readWrite', db: 'JestDB' }] })
            db.createCollection('test-collection');
          EOF
          # Do whatever you like in here

    # do some other stuff, like setting up your build tools

      - name: Test
        run: |
          echo "Run your integration Tests"
     
    # ...  
